package com.automl.datarepresentation;

import java.util.Map;
import java.util.TreeMap;

/** Veuillez noter que l'auto generation de requet SQL ici est exhaustive,
 * cela, doit retourner une solution correct mais pas du facon performante.
 * une solution performante non exhaustive, besoin de travailler sur les algorithms de graphe
 * ce qui a besoin un peu plus du temps. Vue que notre probleme essentiel n'est pas cette point ici
 * cette solution est semi-automatique. 
 */
public class SQLAutoGenerated {
	
	private static String request = "";
	
	public static void generateRequest(TreeMap<String, Table> tables) {
		
		request = "";
		String select = "SELECT DISTINCT ";
		String from =" From ";
		String where=" Where ";
		
		for (Map.Entry<String, Table> table : tables.entrySet() ) {
			
			table.getValue().generateSelectFromWhere();
			
			select += table.getValue().getSelect();
			from += table.getValue().getFrom();
			
			where += table.getValue().getWhere();
		}
		
		// remove the last comma
		select = select.substring(0, select.length() -2);
		
		// remove the last comma
		from = from.substring(0, from.length() -2);

		// remove the last AND from where
		where = where.substring(0, where.length() -5);

		request = select + "\n"+ from + "\n" + where;
		
	}

	/**
	 * @return the request
	 */
	public static String getRequest() {
		return request;
	}

}
