package com.automl.datarepresentation;

/** Veuillez noter que l'auto generation de requet SQL ici est exhaustive,
 * cela, doit retourner une solution correct mais pas du facon performante.
 * une solution performante non exhaustive, besoin de travailler sur les algorithms de graphe
 * ce qui a besoin un peu plus du temps. Vue que notre probleme essentiel n'est pas cette point ici
 * cette solution est semi-automatique. 
 */
public class SQLAutoGenerated {
	
	
		
}
