package com.automl.datarepresentation.bean;

public class TableOfAutoGeneratedRequest {
	
	String[][] data;
	String[] colomnName;
	/**
	 * @return the data
	 */
	public String[][] getData() {
		return data;
	}
	/**
	 * @param data the data to set
	 */
	public void setData(String[][] data) {
		this.data = data;
	}
	/**
	 * @return the colomnName
	 */
	public String[] getColomnName() {
		return colomnName;
	}
	/**
	 * @param colomnName the colomnName to set
	 */
	public void setColomnName(String[] colomnName) {
		this.colomnName = colomnName;
	}
}
